### ISSUE TITLE
wrong link at Computational Linguistics for Political and Social Sciences (CPSS 2023)

### ISSUE THREAD

**Issue by SoaresAlisson** [chkla/css-events#2]
Nice Job this list! 

At last for me, the link of "Computational Linguistics for Political and Social Sciences (CPSS 2023)" in Ingolstadt, Germany / Hybrid  is broken. I found this https://sites.google.com/view/cpss2023konvens/home-page 

Best regards

**Comment by chkla** [comment]
Thank you so much for catching that and providing the correct link! I've just updated the "Computational Linguistics for Political and Social Sciences (CPSS 2023)" link with the one you shared. Your help makes this list even better. Really appreciate it :)
